#ifndef _BRICK_TYPEDEFS_H_
#define _BRICK_TYPEDEFS_H_

#include "AmiFlash.h"

typedef struct _AMI_FLASH_PROTOCOL AMI_SMM_FLASH_PROTOCOL;
typedef AMI_DEBUG_SERVICE_PROTOCOL AMI_SMM_DEBUG_SERVICE_PROTOCOL;

#endif