#ifndef _BRICK_TYPEDEFS_H_
#define _BRICK_TYPEDEFS_H_

#include "AmiFlash.h"
#include "AmiDebugService.h"
#include "AmiNvramUpdate.h"

typedef AMI_FLASH_PROTOCOL AMI_SMM_FLASH_PROTOCOL;
typedef AMI_DEBUG_SERVICE_PROTOCOL AMI_SMM_DEBUG_SERVICE_PROTOCOL;
typedef AMI_NVRAM_UPDATE_PROTOCOL AMI_SMM_NVRAM_UPDATE_PROTOCOL;

#endif